config/routes.rb
Rails.application.routes.draw do
  resources :answers
  resources :comments
  resources :questions
  resources :posts
  devise_for :users
  resources :categories
  get 'home/index'

  root 'home#index'
end

app/models/category.rb
class Category < ApplicationRecord
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if params[:id] != '4'
      @posts = Post.where(category_id: params[:id])
    else
      @posts = Question.all
    end
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :icon)
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= form_for(category) do |f| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :icon %>
    <%= f.text_field :icon %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class = "categories-wrapper">

  <h1>Categorias</h1>
  <div class = "category-list">
    <% @categories.each do |category| %>
      <div class = "category">
        <% posts = Post.where(category_id: category.id) %>
        <%= link_to category.name, category, class: "category-description" %>
        <%= link_to image_tag(category.icon), category %>
        <p class = "post-count">Posts: <%= posts.count %></p>
        <% if posts.count > 0 %>
          <%= link_to 'Ultimo post: ' + Post.where(category_id: category.id).last.title, Post.where(category_id: category.id).last, class: 'last-post' %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<div class = "category-show-wrapper">
  <div class = "top-content">
    <h1><%=@category.name%></h1>
    <% if @category.id != 4%>
      <%= link_to 'Enviar nova receita',new_post_path %>
    <% else %>
      <%= link_to 'Enviar nova dúvida',new_question_path %>
    <% end %>
  </div>
  <% @contador = 0%>
  <% @posts.each do |post| %>
    <%if @contador%2 == 0 %>
      <div class = "row">
    <% end %>
    <div class = "col-4 offset-1 reciple-item">
      <% @author = User.where(id: post.user_id)[0]%>
      <% @answers = Comment.where(post_id: post.id).count %>
      <%= link_to image_tag(@author.avatar), post, class:'user-avatar' %>
      <div class = "reciple-details">
        <%= link_to post.title, post, class: 'post-title' %>
        <p> Respostas: <%= @answers %> </p>
        <p class = "author"><%= 'Criado Por: ' + @author.nickname %></p>
        <p class = "date"><%=post.created_at.to_date.strftime "%d/%m/%Y" %></p> 
      </div>
    </div>
    <%@contador += 1 %>
    <%if @contador%2 == 0 %>
      </div>
    <% end %>
  <% end %>
</div>